// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "commands/build.mdx": () => import("../content/docs/commands/build.mdx?collection=docs"), "commands/completions.mdx": () => import("../content/docs/commands/completions.mdx?collection=docs"), "commands/config.mdx": () => import("../content/docs/commands/config.mdx?collection=docs"), "commands/init.mdx": () => import("../content/docs/commands/init.mdx?collection=docs"), "commands/plan.mdx": () => import("../content/docs/commands/plan.mdx?collection=docs"), "commands/pr.mdx": () => import("../content/docs/commands/pr.mdx?collection=docs"), "commands/run.mdx": () => import("../content/docs/commands/run.mdx?collection=docs"), "commands/status.mdx": () => import("../content/docs/commands/status.mdx?collection=docs"), "commands/team-build.mdx": () => import("../content/docs/commands/team-build.mdx?collection=docs"), "commands/update.mdx": () => import("../content/docs/commands/update.mdx?collection=docs"), "guides/checkpoint-recovery.mdx": () => import("../content/docs/guides/checkpoint-recovery.mdx?collection=docs"), "guides/cross-platform.mdx": () => import("../content/docs/guides/cross-platform.mdx?collection=docs"), "guides/github-integration.mdx": () => import("../content/docs/guides/github-integration.mdx?collection=docs"), "guides/interactive-mode.mdx": () => import("../content/docs/guides/interactive-mode.mdx?collection=docs"), "guides/model-tiering.mdx": () => import("../content/docs/guides/model-tiering.mdx?collection=docs"), "guides/plan-templates.mdx": () => import("../content/docs/guides/plan-templates.mdx?collection=docs"), "guides/token-tracking.mdx": () => import("../content/docs/guides/token-tracking.mdx?collection=docs"), "guides/webhook-notifications.mdx": () => import("../content/docs/guides/webhook-notifications.mdx?collection=docs"), "getting-started/configuration.mdx": () => import("../content/docs/getting-started/configuration.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "reference/agent-types.mdx": () => import("../content/docs/reference/agent-types.mdx?collection=docs"), "reference/checkpoint-format.mdx": () => import("../content/docs/reference/checkpoint-format.mdx?collection=docs"), "reference/kova-yaml.mdx": () => import("../content/docs/reference/kova-yaml.mdx?collection=docs"), "reference/plan-format.mdx": () => import("../content/docs/reference/plan-format.mdx?collection=docs"), }),
};
export default browserCollections;